---
# Network Infrastructure
- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: http://192.168.50.5/admin
        description: DNS & Ad Blocking
        
    - Synology NAS:
        icon: synology.png
        href: http://192.168.50.92:5000
        description: DS243+ Storage Server
        
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://localhost:3031
        description: Service Monitoring
        
    - Netdata:
        icon: netdata.png
        href: http://localhost:19999
        description: Real-time Performance Monitoring

# Media Services
- Media:
    - Plex:
        icon: plex.png
        href: http://192.168.50.92:32400/web
        description: Media Server
        
    - Radarr:
        icon: radarr.png
        href: http://192.168.50.92:7878
        description: Movie Management
        
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.50.92:8989
        description: TV Show Management
# Network Monitoring
- Network:
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        href: http://localhost:3032
        description: Internet Speed Monitoring
        widget:
          type: customapi
          url: http://speedtest-tracker:80/api/speedtest/latest
          method: GET
          mappings:
            - field: data.download
              label: Download
              format: float
              suffix: " Mbps"
            - field: data.upload  
              label: Upload
              format: float
              suffix: " Mbps"
            - field: data.ping
              label: Ping
              format: float
              suffix: " ms"