---
# Network Infrastructure
- Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: http://192.168.50.5/admin
        description: DNS & Ad Blocking
        
    - Synology NAS:
        icon: synology.png
        href: http://192.168.50.92:5000
        description: DS243+ Storage Server
        
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://localhost:3031
        description: Service Monitoring
        
    - Netdata:
        icon: netdata.png
        href: http://localhost:19999
        description: Real-time Performance Monitoring

# Media Services
- Media:
    - Plex:
        icon: plex.png
        href: http://192.168.50.92:32400/web
        description: Media Server
        widget:
          type: plex
          url: http://192.168.50.92:32400
          key: QWQEjkGeKFsy3eQUYB1-
        
    - Overseerr:
        icon: overseerr.png
        href: http://192.168.50.92:5055
        description: Media Requests
        widget:
          type: overseerr
          url: http://192.168.50.92:5055
          key: MTc0NzY0ODMxOTM3NDc4NTdlYTEyLWNhN2YtNGRhYS05M2VkLTU5YzIyZWFmZDNkMQ==
        
    - Radarr:
        icon: radarr.png
        href: http://192.168.50.92:7878
        description: Movie Management
        widget:
          type: radarr
          url: http://192.168.50.92:7878
          key: 1796ecf4c4f244bfa6b7db47c6e271b0
        
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.50.92:8989
        description: TV Show Management
        widget:
          type: sonarr
          url: http://192.168.50.92:8989
          key: 8709f14bd30d4924bc76349878a1a06f
        
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.50.92:9696
        description: Indexer Management
        widget:
          type: prowlarr
          url: http://192.168.50.92:9696
          key: 06329eca76a94f1a8b43322aeff38031

# Download Services
- Downloads:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://192.168.50.92:8090
        description: Torrent Client (via VPN)
        widget:
          type: qbittorrent
          url: http://192.168.50.92:8090
          username: kevin
          password: kevinkevin
        
    - VaderFlix:
        icon: mdi-movie-roll
        href: http://192.168.50.92:8091
        description: Custom Media App

# Network Monitoring
- Network:
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        href: http://localhost:3032
        description: Internet Speed Monitoring
        widget:
          type: customapi
          url: http://speedtest-tracker:80/api/speedtest/latest
          method: GET
          mappings:
            - field: data.download
              label: Download
              format: float
              suffix: " Mbps"
            - field: data.upload  
              label: Upload
              format: float
              suffix: " Mbps"
            - field: data.ping
              label: Ping
              format: float
              suffix: " ms"

# System Services
- System:
    - FlareSolverr:
        icon: flaresolverr.png
        href: http://192.168.50.92:8191
        description: Cloudflare Bypass
        
    - Gluetun:
        icon: mdi-vpn
        href: http://192.168.50.92:8090
        description: VPN Container
        
    - Watchtower:
        icon: watchtower.png
        href: #
        description: Auto-update Containers