services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3030:3000"
    volumes:
      - ${PWD}/../config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=localhost:3030,homepage:3030,192.168.*.*:3030
    group_add:
      - 986  # docker group
    restart: unless-stopped
    
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3031:3001"
    volumes:
      - ${PWD}/../config/uptime-kuma:/app/data
    restart: unless-stopped
    
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${PWD}/../config/netdata:/etc/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PGID=986  # docker group
    restart: unless-stopped

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    ports:
      - "3032:80"
    volumes:
      - ${PWD}/../config/speedtest-tracker:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - APP_KEY=base64:a9P5YUuFTgCIEJk0cZuh4GPPJ0z96UolwGvZKOW72L8=
      - APP_URL=http://localhost:3032
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 * * * *"
    restart: unless-stopped
  dashy:
    image: lissy93/dashy
    container_name: dashy
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/../config/dashy/conf.yml:/app/user-data/conf.yml
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=21600
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
