services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3030:3000"
    volumes:
      - ${PWD}/../config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=localhost:3030,homepage:3030,192.168.*.*:3030
    group_add:
      - 986  # docker group
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3031:3001"
    volumes:
      - ${PWD}/../config/uptime-kuma:/app/data
    restart: unless-stopped
